import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { pathToFileURL,fileURLToPath } from "node:url";
import { spawn,spawnSync } from "node:child_process";
import type Database from "better-sqlite3";
import type { CommerceSale } from "../src/lib/commerce-types";
const root=process.env.INTERNAL_SOURCE_ROOT||process.cwd(),out=process.env.MERGE_EVIDENCE||"/tmp";
const fixture=process.env.COMMERCE_TEST_FIXTURE||fs.mkdtempSync("/tmp/xt-aftercare-test-");fs.mkdirSync(out,{recursive:true});
const seedMode=process.argv.includes("--seed-before"),workerMode=process.argv.includes("--worker");
Object.assign(process.env,{NODE_ENV:"test",DB_PATH:path.join(fixture,"synthetic.db"),INTERNAL_APP_ROOT:root,COMMERCE_PILOT_ENABLED:"1",JWT_SECRET:"local-merge-test-key",CUSTOMER_SYNC_URL:"",SYNC_SECRET:""});process.chdir(fixture);
const require=createRequire(path.join(root,"package.json")),{NextRequest}=require("next/server") as typeof import("next/server"),bcrypt=require("bcryptjs") as typeof import("bcryptjs");
const loader="/Users/liuyujiang/湘泰业务网站/node_modules/tsx/dist/loader.mjs",self=fileURLToPath(import.meta.url);
const load=(relative:string)=>import(pathToFileURL(path.join(root,relative)).href);
type Row=Record<string,unknown>;const calls:Row[]=[],groups:Row[]=[],children:Row[]=[];let users:Record<string,{id:number;token:string}>={};
type Handler=(req:InstanceType<typeof NextRequest>,ctx:{params:Promise<{id:string;cancellationId:string}>})=>Promise<Response>;
async function call(route:string,method:string,role?:string,body?:unknown,status=200,id="",cid="",query=""){
 const mod=await load("src/app/api/"+route+"/route.ts") as Record<string,Handler>,headers:Record<string,string>={};if(role)headers.Authorization="Bearer "+users[role].token;if(body!==undefined)headers["Content-Type"]="application/json";
 const r=await mod[method](new NextRequest("http://127.0.0.1/api/"+route+query,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),{params:Promise.resolve({id,cancellationId:cid})});const text=await r.text();calls.push({route,query,method,role:role||null,input:body??null,status:r.status,output:text,id,cid});assert.equal(r.status,status,text);return JSON.parse(text);
}
async function group(name:string,fn:()=>Promise<void>){try{await fn();groups.push({name,passed:true});console.log("PASS "+name);}catch(e){groups.push({name,passed:false,error:String(e)});console.error("FAIL "+name,e);}}
const env=(source:string):NodeJS.ProcessEnv=>({NODE_ENV:"test",PATH:process.env.PATH,HOME:process.env.HOME,LANG:"en_US.UTF-8",TMPDIR:"/tmp",COMMERCE_TEST_FIXTURE:fixture,INTERNAL_SOURCE_ROOT:source,TSX_TSCONFIG_PATH:path.join(source,"tsconfig.json"),MERGE_EVIDENCE:out});
if(!seedMode&&!workerMode){const source=process.env.COMMERCE_PREVIOUS_ROOT||root,args=["--import",loader,self,"--seed-before"],environment=env(source);const r=spawnSync(process.execPath,args,{env:environment,cwd:fixture,encoding:"utf8",timeout:90000});children.push({argv:[process.execPath,...args],cwd:fixture,env:environment,exit_status:r.status,stdout:r.stdout,stderr:r.stderr});assert.equal(r.status,0,r.stderr);fs.copyFileSync(path.join(fixture,"synthetic.db"),path.join(fixture,"before.db"));}
const {getDb}=await load("src/lib/db.ts") as typeof import("../src/lib/db");const db=getDb();
function snapshot(d:Database.Database=db){const tables=d.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all() as {name:string}[];return Object.fromEntries(tables.map(t=>[t.name,d.prepare('SELECT rowid,* FROM "'+t.name.replaceAll('"','""')+'" ORDER BY rowid').all()]));}
let seq=0;const rid=()=>"aftercare-request-"+String(++seq).padStart(5,"0");
if(seedMode){
 for(const [name,role] of [["admin","admin"],["staff","employee"],["a","client"],["b","client"]]){const id=Number(db.prepare("INSERT INTO employees(name,email,role,password,must_change_password) VALUES (?,?,?,?,0)").run(role==="client"?"SAME BUYER":name,name+"@example.test",role,bcrypt.hashSync("SyntheticPass!42",4)).lastInsertRowid);db.prepare("INSERT INTO client_scope_settings(employee_id,mode) VALUES (?,'explicit')").run(id);const login=await call("auth/login","POST",undefined,{email:name+"@example.test",password:"SyntheticPass!42"});users[name]={id,token:login.token};}
 const products=[];for(const [sku,price]of [["COM-001",12345],["TRA-006",34567]])products.push(await call("commerce/products","POST","admin",{sku,name:"Synthetic "+sku,price_cents:price,active:true},201));
 const lines=products.map(p=>({product_id:p.id,quantity:2,revision:p.revision,terms_version:p.terms.version}));const request={request_id:"prior-aftercare-purchase-0001",lines};const sale=(await call("commerce/orders","POST","a",request,201)).sale;await call("commerce/orders/[id]/payment","POST","admin",{payment_reference:"PRIOR-AFTERCARE-PAID"},200,sale.id);await call("commerce/cart","PUT","a",{revision:0,lines});
 fs.writeFileSync(path.join(fixture,"seed.json"),JSON.stringify({users,products,request,sale,snapshot:snapshot(),calls,oldSchema:!db.prepare("SELECT 1 FROM sqlite_master WHERE name='commerce_cancellations'").get()}));console.log("BASELINE "+JSON.stringify({paid:true,sale_id:sale.id,cancel_route_exists:fs.existsSync(path.join(root,"src/app/api/commerce/orders/[id]/cancellations/route.ts"))}));db.close();process.exit(0);
}
const seed=JSON.parse(fs.readFileSync(path.join(fixture,"seed.json"),"utf8"));users=seed.users;
if(workerMode){const v=JSON.parse(process.argv[process.argv.indexOf("--worker")+1]);const mod=await load("src/app/api/"+v.route+"/route.ts") as Record<string,Handler>;const r=await mod.POST(new NextRequest("http://127.0.0.1/api/worker",{method:"POST",headers:{Authorization:"Bearer "+users.admin.token,"Content-Type":"application/json"},body:JSON.stringify(v.body)}),{params:Promise.resolve({id:v.id,cancellationId:v.cid||""})});console.log("WORKER "+JSON.stringify({status:r.status,output:await r.json()}));db.close();process.exit(0);}
const mutate=(action:string,role:string,sale:CommerceSale,body:unknown,status=201,cid="")=>call("commerce/orders/[id]/"+action,"POST",role,body,status,sale.id,cid);
const saleRead=(id:string,role="a")=>call("commerce/orders/[id]","GET",role,undefined,200,id) as Promise<CommerceSale>;
async function buy(role="a",quantities=[1,2]):Promise<CommerceSale>{const lines=seed.products.map((p:{id:string;revision:number;terms:{version:string}},i:number)=>({product_id:p.id,quantity:quantities[i],revision:p.revision,terms_version:p.terms.version})).filter((p:{quantity:number})=>p.quantity);return (await call("commerce/orders","POST",role,{request_id:rid(),lines},201)).sale;}
const fsale=(sale:CommerceSale)=>sale.lines.flatMap(l=>l.fulfillments);
const cancel=(sale:CommerceSale,ids:string[],reason="客户申请部分取消")=>mutate("cancellations","a",sale,{request_id:rid(),order_ids:ids,reason}) as Promise<CommerceSale>;
const approve=(sale:CommerceSale,credits:{order_id:string;credit_cents:number}[],cid=sale.cancellations.find(c=>c.status==="pending")!.id)=>mutate("cancellations/[cancellationId]/decision","admin",sale,{request_id:rid(),revision:sale.billing.revision,decision:"approve",public_note:"管理员确认本次服务取消和明确减免",credits},201,cid) as Promise<CommerceSale>;
async function pay(sale:CommerceSale){return await call("commerce/orders/[id]/payment","POST","admin",{payment_reference:rid(),revision:sale.billing.revision},200,sale.id) as CommerceSale;}
const immutable=(id:string)=>({sale:db.prepare("SELECT * FROM commerce_sales WHERE id=?").get(id),lines:db.prepare("SELECT * FROM commerce_lines WHERE sale_id=? ORDER BY line_no").all(id),invoice:db.prepare("SELECT id,sale_id,total_cents,currency,created_at FROM commerce_invoices WHERE sale_id=?").get(id)});
async function worker(v:Row){return new Promise<{status:number;output:CommerceSale}>((resolve,reject)=>{const args=["--import",loader,self,"--worker",JSON.stringify(v)],environment=env(root),p=spawn(process.execPath,args,{cwd:fixture,env:environment,timeout:45000});let stdout="",stderr="";p.stdout.on("data",x=>{stdout+=x;});p.stderr.on("data",x=>{stderr+=x;});p.on("error",reject);p.on("close",code=>{children.push({argv:[process.execPath,...args],cwd:fixture,env:environment,exit_status:code,stdout,stderr});try{assert.equal(code,0,stderr);const line=stdout.split("\n").find(x=>x.startsWith("WORKER "));assert(line,stdout);resolve(JSON.parse(line.slice(7)));}catch(e){reject(e);}});});}
try{
await group("upgrade v3 preserves all existing rows, paid receipts, immutable terms and active cart",async()=>{const now=snapshot();for(const [table,rows]of Object.entries(seed.snapshot))assert.deepEqual(now[table],rows,table);const sale=await saleRead(seed.sale.id);assert.equal(sale.billing.original_cents,93824);assert.equal(sale.billing.received_cents,93824);assert.equal(sale.billing.settlement,"paid");assert.deepEqual(sale.cancellations,[]);assert.deepEqual(db.pragma("foreign_key_check"),[]);});
await group("customer request is buyer-owned, idempotent, non-pausing, and rejects duplicate or cross-sale copies",async()=>{
 let s=await buy();const f=fsale(s)[0],before=immutable(s.id),steps=db.prepare("SELECT * FROM order_steps WHERE order_id=?").all(f.order_id);const input={request_id:rid(),order_ids:[f.order_id],reason:"请取消本份"};s=await mutate("cancellations","a",s,input);assert.equal(s.cancellations[0].status,"pending");assert.equal(fsale(s)[0].status,f.status);assert.deepEqual(immutable(s.id),before);assert.deepEqual(db.prepare("SELECT * FROM order_steps WHERE order_id=?").all(f.order_id),steps);
 const state=snapshot();await mutate("cancellations","a",s,input);assert.deepEqual(snapshot(),state);await mutate("cancellations","a",s,{...input,reason:"改内容"},409);await mutate("cancellations","a",s,{...input,request_id:rid()},409);await mutate("cancellations","b",s,input,404);await mutate("cancellations","staff",s,input,403);await mutate("cancellations","a",s,{...input,buyer_account_id:users.b.id},400);const other=await buy("b");await mutate("cancellations","a",s,{request_id:rid(),order_ids:[fsale(other)[0].order_id],reason:"错误范围"},404);
});
await group("withdraw and rejection preserve business and money, allow new application, and cannot overwrite an existing decision",async()=>{
 let s=await buy();const ids=[fsale(s)[0].order_id];s=await cancel(s,ids);let cid=s.cancellations[0].id;const withdraw={request_id:rid()};s=await mutate("cancellations/[cancellationId]/withdraw","a",s,withdraw,201,cid);assert.equal(s.cancellations[0].status,"withdrawn");await mutate("cancellations/[cancellationId]/withdraw","a",s,withdraw,201,cid);await mutate("cancellations/[cancellationId]/decision","admin",s,{request_id:rid(),revision:s.billing.revision,decision:"reject",public_note:"迟到决定",credits:[]},409,cid);
 s=await cancel(s,ids);cid=s.cancellations.find(c=>c.status==="pending")!.id;const no={request_id:rid(),revision:s.billing.revision,decision:"reject",public_note:"按约继续办理",credits:[]};s=await mutate("cancellations/[cancellationId]/decision","admin",s,no,201,cid);assert(s.cancellations.some(c=>c.status==="rejected"));assert.equal(s.billing.credited_cents,0);assert.notEqual(fsale(s)[0].status,"客户取消");await mutate("cancellations/[cancellationId]/withdraw","a",s,{request_id:rid()},409,cid);s=await cancel(s,ids);assert(s.cancellations.some(c=>c.status==="pending"));
});
await group("approve one unpaid trademark copy with explicit partial credit: other copies continue and only net amount is collected",async()=>{
 let s=await buy();const f=s.lines.find(l=>l.sku==="TRA-006")!.fulfillments[0],before=immutable(s.id);s=await cancel(s,[f.order_id]);const cid=s.cancellations[0].id;
 await mutate("cancellations/[cancellationId]/decision","staff",s,{request_id:rid(),revision:s.billing.revision,decision:"approve",public_note:"越权",credits:[{order_id:f.order_id,credit_cents:30000}]},403,cid);
 s=await approve(s,[{order_id:f.order_id,credit_cents:30000}]);assert.equal(s.billing.adjusted_cents,51479);assert.equal(fsale(s).filter(f=>f.status==="客户取消").length,1);assert.equal(s.billing.received_cents,0);assert.equal(s.billing.refunded_cents,0);assert.deepEqual(immutable(s.id),before);
 await call("commerce/orders/[id]/payment","POST","admin",{payment_reference:rid()},400,s.id);s=await pay(s);assert.equal(s.billing.received_cents,51479);assert.equal(s.billing.balance_due_cents,0);assert.equal(s.billing.allocations.find(a=>a.order_id===f.order_id)!.received_cents,4567);assert.deepEqual(immutable(s.id),before);
});
await group("approved native cancellation freezes work states, preserves notes and other copies, even with pilot off",async()=>{
 let s=await buy();const [f,other]=fsale(s);s=await cancel(s,[f.order_id]);
 await call("orders/[id]/steps","PATCH","staff",{step_id:f.steps[0].id,status:"进行中"},200,f.order_id);
 s=await approve(s,[{order_id:f.order_id,credit_cents:0}]);
 const before=db.prepare("SELECT * FROM order_steps WHERE order_id=? ORDER BY id").all(f.order_id);
 for(const status of ["待处理","进行中","已完成","阻塞"])await call("orders/[id]/steps","PATCH","staff",{step_id:f.steps[0].id,status},409,f.order_id);
 assert.deepEqual(db.prepare("SELECT * FROM order_steps WHERE order_id=? ORDER BY id").all(f.order_id),before);
 await call("orders/[id]/steps","PATCH","staff",{step_id:f.steps[0].id,notes:"取消后补充说明",assignee:"staff"},200,f.order_id);
 await call("orders/[id]/steps","PATCH","staff",{step_id:other.steps[0].id,status:"进行中"},200,other.order_id);
 process.env.COMMERCE_PILOT_ENABLED="0";
 try{await call("orders/[id]/steps","PATCH","admin",{step_id:f.steps[0].id,status:"已完成"},409,f.order_id);}finally{process.env.COMMERCE_PILOT_ENABLED="1";}
 const final=await saleRead(s.id);assert.equal(fsale(final)[0].status,"客户取消");assert.equal(fsale(final)[1].status,"进行中");
});
await group("full unpaid credit voids collection without deleting bill or historical workflow",async()=>{let s=await buy("a",[1,0]);const before=immutable(s.id);s=await cancel(s,fsale(s).map(f=>f.order_id));s=await approve(s,s.billing.allocations.map(a=>({order_id:a.order_id,credit_cents:a.original_cents})));assert.equal(s.billing.settlement,"voided");assert.equal(s.billing.received_cents,0);await call("commerce/orders/[id]/payment","POST","admin",{payment_reference:rid(),revision:s.billing.revision},409,s.id);assert.deepEqual(immutable(s.id),before);assert.equal((db.prepare("SELECT COUNT(*) n FROM commerce_invoices WHERE sale_id=?").get(s.id) as {n:number}).n,1);});
await group("paid cancellation creates refund due but no automatic cash movement; actual partial refunds and replay are bounded",async()=>{
 let s=await pay(await buy("a",[0,2]));const f=fsale(s)[0],before=immutable(s.id);s=await cancel(s,[f.order_id]);s=await approve(s,[{order_id:f.order_id,credit_cents:30000}]);assert.equal(s.billing.refund_due_cents,30000);assert.equal(s.billing.refunded_cents,0);assert.equal(s.billing.settlement,"refund_due");
 const input={request_id:rid(),revision:s.billing.revision,reason:"实际退款第一笔",reference:rid(),items:[{order_id:f.order_id,amount_cents:12345}],transferred:true};await mutate("refunds","staff",s,input,403);await mutate("refunds","admin",s,{...input,transferred:false},400);await mutate("refunds","admin",s,{...input,items:[{order_id:f.order_id,amount_cents:30001}]},400);
 s=await mutate("refunds","admin",s,input);assert.equal(s.billing.refunded_cents,12345);assert.equal(s.billing.refund_due_cents,17655);const state=snapshot();await mutate("refunds","admin",s,input);assert.deepEqual(snapshot(),state);await mutate("refunds","admin",s,{...input,request_id:rid(),revision:s.billing.revision},409);
 s=await mutate("refunds","admin",s,{...input,request_id:rid(),revision:s.billing.revision,reference:rid(),items:[{order_id:f.order_id,amount_cents:17655}]});assert.equal(s.billing.refund_due_cents,0);assert.equal(s.billing.settlement,"paid");assert.deepEqual(immutable(s.id),before);
 const finance=(db.prepare("SELECT finance_id FROM commerce_refund_items WHERE order_id=?").get(f.order_id) as {finance_id:number}).finance_id;for(const method of ["PATCH","DELETE"])await call("orders/[id]/finances",method,"admin",{finance_id:finance,amount:1},409,f.order_id);const rows=await call("orders/[id]/finances","GET","staff",undefined,200,f.order_id);assert.equal(rows.filter((r:{commerce_refund:boolean})=>r.commerce_refund).length,2);
 const all=await call("finances","GET","staff");assert.equal(all.filter((r:{order_id:string;commerce_refund:boolean})=>r.order_id===f.order_id&&r.commerce_refund).length,2);await call("finances","GET","a",undefined,403);
});
await group("admin additional credits are append-only, capped per copy and require fresh revision; customer cannot forge refund amounts",async()=>{
 let s=await pay(await buy("a",[1,0]));const f=fsale(s)[0],input={request_id:rid(),revision:s.billing.revision,reason:"单独核实后减免",credits:[{order_id:f.order_id,credit_cents:12345}]};await mutate("adjustments","a",s,input,403);await mutate("adjustments","staff",s,input,403);for(const n of [-1,0,0.1,12346,"100"])await mutate("adjustments","admin",s,{...input,credits:[{order_id:f.order_id,credit_cents:n}]},400);
 s=await mutate("adjustments","admin",s,input);const state=snapshot();await mutate("adjustments","admin",s,input);assert.deepEqual(snapshot(),state);await mutate("adjustments","admin",s,{...input,request_id:rid()},409);s=await mutate("refunds","admin",s,{request_id:rid(),revision:s.billing.revision,reference:rid(),reason:"全额已退",transferred:true,items:[{order_id:f.order_id,amount_cents:12345}]});assert.equal(s.billing.settlement,"refunded");assert.equal(fsale(s)[0].status,"待处理");
});
await group("completed or differently scoped service is never cancelled by stale approval, and unknown credit allocation is rejected",async()=>{let s=await buy();const f=fsale(s)[0];s=await cancel(s,[f.order_id]);const cid=s.cancellations[0].id,input={request_id:rid(),revision:s.billing.revision,decision:"approve",public_note:"批准本份",credits:[{order_id:fsale(s)[1].order_id,credit_cents:1}]};await mutate("cancellations/[cancellationId]/decision","admin",s,input,400,cid);for(const step of f.steps)await call("orders/[id]/steps","PATCH","staff",{step_id:step.id,status:"已完成"},200,f.order_id);await mutate("cancellations/[cancellationId]/decision","admin",s,{...input,credits:[{order_id:f.order_id,credit_cents:0}]},409,cid);assert.equal((await saleRead(s.id)).cancellations[0].status,"pending");});
await group("faults at request items, approval credit, refund finance, and audit leave no partial cancellation, ledger or income",async()=>{
 let s=await buy();const f=fsale(s)[0];let before=snapshot();db.exec("CREATE TRIGGER fail_aftercare BEFORE INSERT ON commerce_cancellation_items BEGIN SELECT RAISE(ABORT,'CANCEL ITEM FAULT'); END");await mutate("cancellations","a",s,{request_id:rid(),order_ids:[f.order_id],reason:"故障测试"},500);db.exec("DROP TRIGGER fail_aftercare");assert.deepEqual(snapshot(),before);
 s=await pay(s);s=await cancel(s,[f.order_id]);const cid=s.cancellations[0].id;
 for(const target of ["commerce_adjustment_items","audit_logs"]){before=snapshot();db.exec(`CREATE TRIGGER fail_aftercare BEFORE INSERT ON ${target} BEGIN SELECT RAISE(ABORT,'APPROVAL FAULT'); END`);await mutate("cancellations/[cancellationId]/decision","admin",s,{request_id:rid(),revision:s.billing.revision,decision:"approve",public_note:"故障测试",credits:[{order_id:f.order_id,credit_cents:100}]},500,cid);db.exec("DROP TRIGGER fail_aftercare");assert.deepEqual(snapshot(),before);}
 s=await approve(s,[{order_id:f.order_id,credit_cents:100}]);before=snapshot();db.exec("CREATE TRIGGER fail_aftercare BEFORE INSERT ON commerce_refund_items BEGIN SELECT RAISE(ABORT,'REFUND ITEM FAULT'); END");await mutate("refunds","admin",s,{request_id:rid(),revision:s.billing.revision,reason:"故障退款",reference:rid(),items:[{order_id:f.order_id,amount_cents:100}],transferred:true},500);db.exec("DROP TRIGGER fail_aftercare");assert.deepEqual(snapshot(),before);
});
await group("two processes racing payment and approval use one revision so only one commits",async()=>{let s=await buy();const f=fsale(s)[0];s=await cancel(s,[f.order_id]);const cid=s.cancellations[0].id,revision=s.billing.revision;const all=await Promise.allSettled([worker({route:"commerce/orders/[id]/payment",id:s.id,body:{payment_reference:rid(),revision}}),worker({route:"commerce/orders/[id]/cancellations/[cancellationId]/decision",id:s.id,cid,body:{request_id:rid(),revision,decision:"approve",public_note:"并发处理",credits:[{order_id:f.order_id,credit_cents:100}]}})]);const results=all.map(r=>{if(r.status==='rejected')throw r.reason;return r.value;});assert.equal(results.filter(r=>r.status===409).length,1);assert.equal(results.filter(r=>r.status===200||r.status===201).length,1);const current=await saleRead(s.id);assert.equal(current.billing.revision,revision+1);});
await group("two independent refund submissions never record the same balance twice",async()=>{let s=await pay(await buy("a",[1,0]));const f=fsale(s)[0];s=await mutate("adjustments","admin",s,{request_id:rid(),revision:s.billing.revision,reason:"并发退款准备",credits:[{order_id:f.order_id,credit_cents:100}]});const make=()=>({route:"commerce/orders/[id]/refunds",id:s.id,body:{request_id:rid(),revision:s.billing.revision,reference:rid(),reason:"实退核对",items:[{order_id:f.order_id,amount_cents:100}],transferred:true}});const all=await Promise.allSettled([worker(make()),worker(make())]);const results=all.map(r=>{if(r.status==='rejected')throw r.reason;return r.value;});assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal((await saleRead(s.id)).billing.refunded_cents,100);});
await group("pagination reaches older than 100 sales, is stable with equal timestamps, escapes search and binds current buyer",async()=>{
 for(let i=0;i<105;i++)await buy("b",[1,0]);const ids:string[]=[];let cursor:string|null=null;do{const page=await call("commerce/orders/page","GET","b",undefined,200,"","","?limit=7"+(cursor?'&cursor='+cursor:''));ids.push(...page.items.map((s:CommerceSale)=>s.id));cursor=page.next_cursor;}while(cursor);
 assert.equal(ids.length,new Set(ids).size);assert.equal(ids.length,(db.prepare("SELECT COUNT(*) n FROM commerce_sales WHERE buyer_account_id=?").get(users.b.id) as {n:number}).n);assert(ids.length>100);
 assert.equal((await call("commerce/orders/page","GET","b",undefined,200,"","","?search=%25")).items.length,0);assert.equal((await call("commerce/orders/page","GET","b",undefined,200,"","","?search=TRA-006")).items.length,1);for(const q of ['?limit=0','?limit=51','?cursor=bad','?buyer_account_id='+users.a.id])await call("commerce/orders/page","GET","b",undefined,400,"","",q);
});
await group("pilot off hides new actions and pagination; stored refund protections and customer-file boundaries persist",async()=>{
 const s=await saleRead(seed.sale.id);process.env.COMMERCE_PILOT_ENABLED="0";await mutate("cancellations","a",s,{request_id:rid(),order_ids:[fsale(s)[0].order_id],reason:"closed"},404);await call("commerce/orders/page","GET","a",undefined,404);
 const refund=db.prepare("SELECT finance_id,order_id FROM commerce_refund_items LIMIT 1").get() as {finance_id:number;order_id:string};await call("orders/[id]/finances","DELETE","admin",{finance_id:refund.finance_id},409,refund.order_id);await call("orders/[id]/finances","GET","a",undefined,403,refund.order_id);
 process.env.COMMERCE_PILOT_ENABLED="1";assert.deepEqual(db.pragma("foreign_key_check"),[]);for(const table of ['sync_inbox','sync_orders','sync_progress_outbox'])assert.equal((db.prepare("SELECT count(*) n FROM "+table).get() as {n:number}).n,0);
});
}finally{fs.writeFileSync(path.join(out,"commerce-aftercare-calls.json"),JSON.stringify({root,fixture,old_schema:seed.oldSchema,groups,calls,children,foreign_keys:db.pragma("foreign_key_check")},null,2));db.close();}
console.log(`SUMMARY ${groups.filter(g=>g.passed).length}/${groups.length} groups, ${calls.length} calls`);if(groups.some(g=>!g.passed))process.exitCode=1;
