/** Real route-handler + JWT + fresh SQLite regression. Never imports an existing business DB. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { NextRequest } from 'next/server';
const sourceRoot = path.resolve(process.env.INTERNAL_ACCESS_SOURCE_ROOT || path.join(path.dirname(fileURLToPath(import.meta.url)), '..'));
const output = process.env.INTERNAL_ACCESS_RECORD_DIR;
assert(output && path.isAbsolute(output), 'INTERNAL_ACCESS_RECORD_DIR must be an explicit absolute test evidence directory');
fs.mkdirSync(output, {recursive:true});
const fixture = fs.mkdtempSync(path.join(output, 'synthetic-'));
process.env.DB_PATH = path.join(fixture, 'synthetic.db');
process.env.JWT_SECRET = 'synthetic-local-access-regression';
Object.assign(process.env, { NODE_ENV: 'test' });
process.env.ALLOW_EMPTY_DB = '1';
delete process.env.CUSTOMER_SYNC_URL; delete process.env.SYNC_SECRET;
process.chdir(fixture);fs.mkdirSync('uploads');
globalThis.fetch = async () => { throw new Error('NETWORK_DISABLED_FOR_ACCESS_REGRESSION'); };
const mod = (p:string) => import(path.join(sourceRoot, 'src', p));
const {getDb}=await mod('lib/db.ts');const {signToken}=await mod('lib/auth.ts');const db=getDb();
const identities:Record<string,any>={};
for(const [key,name,role] of [['client','BUYER_A','client'],['other','BUYER_B','client'],['staff','WORKER_A','employee'],['admin','ADMIN_A','admin']]){
 const id=Number(db.prepare('INSERT INTO employees(name,email,role,password,must_change_password,auth_version) VALUES (?,?,?,?,0,0)').run(name,`${key}@test.invalid`,role,'unused').lastInsertRowid);
 identities[key]={id,name,role,token:await signToken({id,name,role,auth_version:0,must_change_password:0})};
}
const ctx=(id:unknown,stepId?:unknown)=>({params:Promise.resolve({id:String(id),...(stepId===undefined?{}:{stepId:String(stepId)})})});
const calls:any[]=[];const results:any[]=[];
function req(url:string,role:string|null,method='GET',body?:unknown){return new NextRequest(`http://127.0.0.1${url}`,{method,headers:{...(role?{authorization:`Bearer ${identities[role].token}`}:{ }), 'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});}
async function call(p:string,method:string,role:string|null='client',body?:unknown,context=ctx('LEGACY-A'),query=''){
 const route=await mod(`app/api/${p}/route.ts`);const response=await route[method](req(`/api/${p}${query}`,role,method,body),context);const text=await response.text();let output:any;try{output=JSON.parse(text)}catch{output=text}
 const record={path:p,method,role,input:body,params:await context.params,query,status:response.status,output};calls.push(record);return record;
}
async function test(name:string,fn:()=>Promise<unknown>){try{results.push({name,status:'PASS',detail:await fn()})}catch(e){results.push({name,status:'FAIL',error:String(e),stack:(e as Error).stack})}console.log(JSON.stringify(results.at(-1)));}
const total=()=>db.prepare('SELECT total_changes() n').get().n;
for(const [id,buyer,source]of [['LEGACY-A','BUYER_A',''],['LEGACY-B','BUYER_B',''],['SYNC-A','BUYER_A','storefront']])db.prepare('INSERT INTO orders(id,customer_name,business_type_id,description,responsible_person,total_amount,source_system) VALUES (?,?,1,?,?,100,?)').run(id,buyer,'PRIVATE_ORDER_NOTE','WORKER_A',source);
const stepA=Number(db.prepare("INSERT INTO order_steps(order_id,step_name,step_order,status,notes) VALUES ('LEGACY-A','Public step',1,'待处理','PRIVATE_STEP_NOTE')").run().lastInsertRowid);
const stepB=Number(db.prepare("INSERT INTO order_steps(order_id,step_name,step_order,status) VALUES ('LEGACY-B','Other step',1,'待处理')").run().lastInsertRowid);
db.prepare("INSERT INTO step_notes(order_id,step_id,content,created_by) VALUES ('LEGACY-A',?,'PRIVATE_NOTE_THREAD','WORKER_A')").run(stepA);
db.prepare("INSERT INTO finances(order_id,type,amount,description) VALUES ('LEGACY-A','expense',37,'PRIVATE_VENDOR_COST')").run();
const vat=Number(db.prepare("INSERT INTO vat_customers(company_name,tax_id) VALUES ('OTHER_VAT','VAT_PRIVATE')").run().lastInsertRowid);
const vr=Number(db.prepare("INSERT INTO vat_records(customer_id,year_month,amount) VALUES (?,'2026-09',765)").run(vat).lastInsertRowid);
const wht=Number(db.prepare("INSERT INTO wht_customers(company_name,tax_id) VALUES ('OTHER_WHT','WHT_PRIVATE')").run().lastInsertRowid);
const wr=Number(db.prepare("INSERT INTO wht_records(customer_id,year_month,subtype,amount) VALUES (?,'2026-09','ภ.ง.ด.53',654)").run(wht).lastInsertRowid);
const inf=Number(db.prepare("INSERT INTO influencers(name,created_by) VALUES ('OTHER_CREATOR','WORKER_A')").run().lastInsertRowid);
const fac=Number(db.prepare("INSERT INTO factories(name,notes) VALUES ('OTHER_FACTORY','PRIVATE_FACTORY_NOTE')").run().lastInsertRowid);
const ship=Number(db.prepare("INSERT INTO shipping_orders(cabinet_number,warehouse,creator) VALUES ('SHIP_A','义乌','WORKER_A')").run().lastInsertRowid);
await test('A1 unrelated VAT/WHT/directory reads are employee-only, without database writes',async()=>{const before=total();for(const [p,c]of [['vat/records/[id]',ctx(vr)],['wht/records/[id]',ctx(wr)],['employees',ctx('')]]as const)assert.equal((await call(p,'GET','client',undefined,c)).status,403);assert.equal(total(),before);return{denied:3,noWrites:true}});
await test('A1 factory/expense/logistics mutations are employee-only',async()=>{const before=total();for(const [p,body,c]of [['factories',{id:fac,notes:'BAD'},ctx('')],['influencers/[id]/finances',{type:'expense',amount:999,status:'paid'},ctx(inf)],['logistics',{cabinet_number:'BAD',warehouse:'义乌'},ctx('')]]as const)assert.equal((await call(p,p==='factories'?'PATCH':'POST','client',body,c)).status,403);assert.equal(total(),before);return{denied:3,noWrites:true}});
await test('A1 feedback token issuance is employee-only, unrelated/sync client routes cannot mint or read',async()=>{const before=total();for(const id of ['LEGACY-A','LEGACY-B','SYNC-A'])for(const method of ['GET','POST'])assert.equal((await call('orders/[id]/feedback-token',method,'client',method==='POST'?{}:undefined,ctx(id))).status,403);assert.equal(total(),before);assert.equal((await call('orders/[id]/feedback-token','POST','staff',{},ctx('MISSING'))).status,404);const valid=await call('orders/[id]/feedback-token','POST','staff',{},ctx('LEGACY-A'));assert.equal(valid.status,201);return{clientDenied:6,staffValid:201,missing:404}});
await test('A2 never-configured legacy account still works; explicit clear stays empty, including repeated clear',async()=>{assert.equal((await call('external/orders/[id]','GET','client',undefined,ctx('LEGACY-A'))).status,200);for(const mapping of [['OTHER'],[],[]]){assert.equal((await call('employees','PATCH','admin',{id:identities.client.id,customer_names:mapping})).status,200);assert.equal((await call('external/orders/[id]','GET','client',undefined,ctx('LEGACY-A'))).status,404)}return{legacy:200,explicitEmpty:404}});
// Subsequent independent cases use an explicit legitimate historical scope.
await call('employees','PATCH','admin',{id:identities.client.id,customer_names:['BUYER_A']});
await test('A2 explicit legacy scope never assigns same-name storefront orders; rename does not regrant',async()=>{assert.equal((await call('orders/[id]','GET','client',undefined,ctx('SYNC-A'))).status,404);assert.equal((await call('external/orders/[id]','GET','client',undefined,ctx('SYNC-A'))).status,404);const list=await call('orders','GET');assert.equal(list.status,200);assert.deepEqual(list.output.map((x:any)=>x.id),['LEGACY-A']);return{syncedDenied:2,legacyList:['LEGACY-A']}});
await test('A3 external+general detail/list share public fields; internal finance and note contents are absent',async()=>{for(const p of ['external/orders/[id]','orders/[id]','external/orders','orders']){const r=await call(p,'GET');assert.equal(r.status,200);const text=JSON.stringify(r.output);assert(!text.includes('PRIVATE_'));assert(!text.includes('WORKER_A'));assert(!text.includes('finances'));assert(!text.includes('responsible_person'))}assert.equal((await call('orders/[id]/finances','GET')).status,403);const ownNotes=await call('orders/[id]/steps/[stepId]/notes','GET','client',undefined,ctx('LEGACY-A',stepA));assert.equal(ownNotes.status,200);assert.deepEqual(ownNotes.output,[]);return{publicRoutes:4,finances:403,ownNotes:[]}});
await test('A4 unregistered logistics file cannot be claimed through document URL; remote/path aliases rejected',async()=>{const filename='logistics-private.pdf';fs.writeFileSync(path.join(fixture,'uploads',filename),'SYNTHETIC_PRIVATE');db.prepare("INSERT INTO shipping_order_files(order_id,name,url,uploaded_by) VALUES (?,'private',?,'WORKER_A')").run(ship,`/api/files/${filename}`);const before=total();for(const url of [`/api/files/${filename}`,`https://other.invalid/api/files/${filename}`,'/api/files/../logistics-private.pdf'])assert.equal((await call('orders/[id]/documents','POST','client',{name:'CLAIM',file_url:url})).status,403);assert.equal(total(),before);const r=await download(filename);assert.equal(r.status,403);return{claimDenied:3,download:403,noWrites:true}});
async function upload(role:string,name='test.pdf'){const route=await mod('app/api/upload/route.ts');const form=new FormData();form.append('file',new File(['%PDF-1.4\nSYNTHETIC_UPLOAD'],name,{type:'application/pdf'}));const response=await route.POST(new NextRequest('http://127.0.0.1/api/upload',{method:'POST',headers:{authorization:`Bearer ${identities[role].token}`},body:form}));const output=await response.json();calls.push({path:'upload',method:'POST',role,input:{name,mime:'application/pdf',bytes:'%PDF-1.4\nSYNTHETIC_UPLOAD'},status:response.status,output});return{status:response.status,output};}
async function download(filename:string,role='client'){const route=await mod('app/api/files/[filename]/route.ts');const r=await route.GET(req(`/api/files/${filename}`,role),{params:Promise.resolve({filename})});const output=await r.text();calls.push({path:'files/[filename]',method:'GET',role,params:{filename},status:r.status,output});return{status:r.status,output};}
await test('A4/A5 real client upload has trustworthy owner; attach is pending/authored by client, own read survives',async()=>{const u=await upload('client');assert.equal(u.status,200);const filename=u.output.url.split('/').pop();assert.equal((await download(filename)).status,200);assert.equal((await download(filename,'other')).status,403);const doc=await call('orders/[id]/documents','POST','client',{name:'Submitted',file_url:u.output.url,status:'已审核',direction:'us_to_client',uploaded_by:'ADMIN_A'});assert.equal(doc.status,201);const saved=db.prepare('SELECT * FROM documents WHERE id=?').get(doc.output.id);assert.equal(saved.status,'待审核');assert.equal(saved.direction,'client_to_us');assert.equal(saved.uploaded_by,'BUYER_A');assert.equal(saved.client_author_id,identities.client.id);const list=await call('orders/[id]/documents','GET');assert(list.output.some((x:any)=>x.id===doc.output.id));return{upload:200,ownRead:200,other:403,savedStatus:saved.status,author:saved.uploaded_by}});
await test('A4 staff-private upload not claimable; old document requires staff verification, legacy certificate still works',async()=>{const u=await upload('staff','private.pdf');assert.equal(u.status,200);const filename=u.output.url.split('/').pop();assert.equal((await download(filename)).status,403);assert.equal((await call('orders/[id]/documents','POST','client',{name:'claim',file_url:u.output.url})).status,403);for(const kind of ['document','certificate']){const file=`public-legacy-${kind}.pdf`;fs.writeFileSync(path.join(fixture,'uploads',file),'PUBLIC_LEGACY');if(kind==='document'){const oldDoc=db.prepare("INSERT INTO documents(order_id,name,status,direction,file_url) VALUES ('LEGACY-A','Public','已审核','us_to_client',?)").run(`/api/files/${file}`);assert.equal((await download(file)).status,403);const approval=await call('orders/[id]/documents','PATCH','staff',{document_id:Number(oldDoc.lastInsertRowid),status:'已审核',direction:'us_to_client'});assert.equal(approval.status,200);assert.equal(approval.output.publication_verified,1)}else db.prepare("INSERT INTO certificates(order_id,certificate_number,file_url,notes) VALUES ('LEGACY-A','CERT-PUBLIC',?,'PRIVATE_CERT_NOTE')").run(`/api/files/${file}`);assert.equal((await download(file)).status,200);assert.equal((await download(file,'other')).status,403)}const certs=await call('orders/[id]/certificates','GET');assert(!JSON.stringify(certs.output).includes('PRIVATE_CERT_NOTE'));return{staffPrivate:403,legacyPublished:2,certNotesHidden:true}});
await test('A4 deletion only removes references, including entire shipping/WHT records; shared bytes survive',async()=>{const file='shared.pdf';const disk=path.join(fixture,'uploads',file);fs.writeFileSync(disk,'SHARED_BYTES');db.prepare("INSERT INTO documents(order_id,name,file_url) VALUES ('LEGACY-A','shared',?)").run(`/api/files/${file}`);const link=await call('logistics/[id]/files','POST','staff',{name:'shared',url:`/api/files/${file}`},ctx(ship));assert.equal(link.status,201);assert.equal((await call('logistics/[id]/files','DELETE','staff',undefined,ctx(ship),`?id=${link.output.id}`)).status,200);assert(fs.existsSync(disk));await call('logistics/[id]/files','POST','staff',{name:'shared',url:`/api/files/${file}`},ctx(ship));assert.equal((await call('logistics/[id]','DELETE','admin',undefined,ctx(ship))).status,200);assert(fs.existsSync(disk));db.prepare("INSERT INTO wht_record_documents(record_id,name,file_url) VALUES (?,'shared',?)").run(wr,`/api/files/${file}`);assert.equal((await call('wht/records/[id]','DELETE','admin',undefined,ctx(wr))).status,200);assert(fs.existsSync(disk));assert(db.prepare('SELECT 1 FROM documents WHERE file_url=?').get(`/api/files/${file}`));return{referenceDelete:200,shippingDelete:200,whtDelete:200,bytes:'SHARED_BYTES'}});
await test('A5 client notes use server identity, client reads only own notes, never staff author/text',async()=>{const note=await call('orders/[id]/steps/[stepId]/notes','POST','client',{content:'MY_NOTE',created_by:'ADMIN_A'},ctx('LEGACY-A',stepA));assert.equal(note.status,201);assert.equal(note.output.created_by,'BUYER_A');const notes=await call('orders/[id]/steps/[stepId]/notes','GET','client',undefined,ctx('LEGACY-A',stepA));assert.equal(notes.status,200);assert.deepEqual(notes.output.map((x:any)=>x.content),['MY_NOTE']);assert(!JSON.stringify(notes.output).includes('PRIVATE_NOTE'));return{author:note.output.created_by,ownNotes:1}});
await test('A6 mismatched order+step rejected before insert for both client/staff; note delete also binds step',async()=>{const before=total();for(const role of ['client','staff'])assert.equal((await call('orders/[id]/steps/[stepId]/notes','POST',role,{content:'CROSS'},ctx('LEGACY-A',stepB))).status,404);assert.equal(total(),before);const stepA2=Number(db.prepare("INSERT INTO order_steps(order_id,step_name,step_order) VALUES ('LEGACY-A','Second own step',2)").run().lastInsertRowid);const note=db.prepare("INSERT INTO step_notes(order_id,step_id,content) VALUES ('LEGACY-A',?,'PROTECT')").run(stepA);assert.equal((await call('orders/[id]/steps/[stepId]/notes','DELETE','staff',{note_id:Number(note.lastInsertRowid)},ctx('LEGACY-A',stepA2))).status,404);assert(db.prepare('SELECT 1 FROM step_notes WHERE id=?').get(note.lastInsertRowid));return{mismatchRejected:2,wrongStepDelete:404}});
await test('live role change, auth version, left status, and forced-password revoke access',async()=>{for(const [sql,status]of [["UPDATE employees SET role='client' WHERE id=?",403],["UPDATE employees SET role='employee',auth_version=1 WHERE id=?",401],["UPDATE employees SET auth_version=0,status='离职' WHERE id=?",401],["UPDATE employees SET status='在职',must_change_password=1 WHERE id=?",401]]as const){db.prepare(sql).run(identities.staff.id);assert.equal((await call('factories','GET','staff')).status,status)}db.prepare("UPDATE employees SET role='employee',must_change_password=0 WHERE id=?").run(identities.staff.id);return{statuses:[403,401,401,401]}});
await test('A4 former staff uploader does not retain employee files after demotion to client',async()=>{
 const uploaded=await upload('staff','staff-before-demotion.pdf');assert.equal(uploaded.status,200);
 const filename=uploaded.output.url.split('/').pop();assert.equal((await download(filename,'staff')).status,200);
 db.prepare("UPDATE employees SET role='client' WHERE id=?").run(identities.staff.id);
 try { assert.equal((await download(filename,'staff')).status,403); }
 finally { db.prepare("UPDATE employees SET role='employee' WHERE id=?").run(identities.staff.id); }
 return{beforeDemotion:200,oldTokenAfterDemotion:403};
});
await test('A2 newly created client starts explicitly unlinked, old never-configured mapping remains separate',async()=>{
 const created=await call('employees','POST','admin',{name:'BUYER_A',email:'new-client@test.invalid',role:'client',password:'SyntheticPassword9!'});assert.equal(created.status,201);
 const {getClientCustomerNames}=await mod('lib/client-scope.ts');assert.deepEqual(getClientCustomerNames(created.output.id,'BUYER_A'),{names:[],legacy:false});
 return{newClient:created.output.id,scope:'explicit-empty'};
});
await test('A2 employee converted to client defaults explicit empty but preserves deliberate existing mappings',async()=>{
 const {getClientCustomerNames}=await mod('lib/client-scope.ts');
 for(const mapped of [false,true]) {
  const created=await call('employees','POST','admin',{name:'BUYER_A',email:`converted-${mapped}@test.invalid`,role:'employee',password:'SyntheticPassword9!'});assert.equal(created.status,201);
  const employeeId=created.output.id;
  if(mapped) assert.equal((await call('employees','PATCH','admin',{id:employeeId,customer_names:['BUYER_A']})).status,200);
  assert.equal((await call('employees','PATCH','admin',{id:employeeId,role:'client'})).status,200);
  assert.deepEqual(getClientCustomerNames(employeeId,'BUYER_A'),{names:mapped?['BUYER_A']:[],legacy:false});
 }
 return{unmapped:'explicit-empty',existingMapping:'preserved'};
});
await test('A4/A5 forged historical document flags are not trusted; explicit staff review is parent-scoped and reversible',async()=>{
 const filename='forged-legacy.pdf';fs.writeFileSync(path.join(fixture,'uploads',filename),'OLD_FLAGS_ARE_NOT_PROOF');
 const docId=Number(db.prepare("INSERT INTO documents(order_id,name,file_url,direction,status,uploaded_by) VALUES ('LEGACY-A','Old forged',?,'us_to_client','已审核','ADMIN_A')").run(`/api/files/${filename}`).lastInsertRowid);
 assert.equal((await download(filename)).status,403);assert(!(await call('orders/[id]/documents','GET')).output.some((x:any)=>x.id===docId));
 assert.equal((await call('orders/[id]/documents','PATCH','client',{document_id:docId,status:'已审核',direction:'us_to_client'})).status,403);
 assert.equal((await call('orders/[id]/documents','PATCH','staff',{document_id:docId,status:'已审核'},ctx('LEGACY-B'))).status,404);
 assert.equal((await call('orders/[id]/documents','PATCH','staff',{document_id:docId,status:'已审核'})).status,200);assert.equal((await download(filename)).status,403);
 assert.equal((await call('orders/[id]/documents','PATCH','staff',{document_id:docId,status:'已审核',direction:'us_to_client'})).status,200);
 assert.equal((await download(filename)).status,200);
 assert.equal((await call('orders/[id]/documents','PATCH','staff',{document_id:docId,status:'待审核'})).status,200);assert.equal((await download(filename)).status,403);
 assert(fs.existsSync(path.join(fixture,'uploads',filename)));return{unverified:403,clientReview:403,wrongParent:404,published:200,withdrawn:403,bytesRetained:true};
});
await test('A6 VAT/WHT/influencer/logistics nested notes preserve normal staff writes but reject wrong parent-step',async()=>{
 const ship2=Number(db.prepare("INSERT INTO shipping_orders(cabinet_number,warehouse,creator) VALUES ('SHIP_B','义乌','WORKER_A')").run().lastInsertRowid);
 const wr2=Number(db.prepare("INSERT INTO wht_records(customer_id,year_month,subtype,amount) VALUES (?,'2026-10','ภ.ง.ด.53',654)").run(wht).lastInsertRowid);
 const entries=[['vat/records/[id]','vat_record_steps','record_id',vr],['wht/records/[id]','wht_record_steps','record_id',wr2],['influencers/[id]','influencer_steps','influencer_id',inf],['logistics/[id]','shipping_steps','order_id',ship2]] as const;
 for(const [prefix,table,parent,parentId]of entries){
  const step=Number(db.prepare(`INSERT INTO ${table}(${parent},step_name,step_order) VALUES (?,'Synthetic',88)`).run(parentId).lastInsertRowid);
  const endpoint=`${prefix}/steps/[stepId]/notes`;const valid=await call(endpoint,'POST','staff',{content:'LEGITIMATE',created_by:'WORKER_A'},ctx(parentId,step));assert.equal(valid.status,201,prefix);
  const before=total();assert.equal((await call(endpoint,'POST','staff',{content:'WRONG_PARENT'},ctx(999999,step))).status,404,prefix);assert.equal(total(),before);
 }
 return{staffNormal201:4,wrongParent404:4};
});
const customerMethods=new Set(['auth/me:GET','auth/change-password:POST','upload:POST','orders:GET','documents:GET','orders/[id]:GET','orders/[id]/documents:GET','orders/[id]/documents:POST','orders/[id]/certificates:GET','orders/[id]/steps/[stepId]/notes:GET','orders/[id]/steps/[stepId]/notes:POST','orders/[id]/steps/[stepId]/documents:GET']);
await test('A1 exhaustive authenticated employee-handler boundary, including _req read-only methods',async()=>{let checked=0;const failures:any[]=[];const root=path.join(sourceRoot,'src/app/api');const routes=fs.readdirSync(root,{recursive:true}).filter((p)=>typeof p==='string'&&p.endsWith('route.ts')) as string[];for(const relative of routes){const source=fs.readFileSync(path.join(root,relative),'utf8');const routePath=relative.replace(/\/route.ts$/,'');const functions=source.split(/(?=export async function (?:GET|POST|PATCH|PUT|DELETE)\()/);for(const fn of functions){const method=/^export async function (\w+)/.exec(fn)?.[1];if(!method||!fn.includes('await verifyAuth(')||customerMethods.has(`${routePath}:${method}`))continue;const before=total();try{const r=await call(routePath,method,'client',['GET','DELETE'].includes(method)?undefined:{},ctx('1','1'));if(r.status!==403||total()!==before)failures.push({routePath,method,status:r.status,writes:total()-before})}catch(e){failures.push({routePath,method,error:String(e)})}checked++;}}
assert.deepEqual(failures,[]);assert(checked>180);return{actualHandlerMethods:checked,allClient403:true,noWrites:true}});
fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({sourceRoot,fixture,results,calls,counts:{pass:results.filter(x=>x.status==='PASS').length,fail:results.filter(x=>x.status==='FAIL').length}},null,2));db.close();console.log(`ACCESS REGRESSION ${results.filter(x=>x.status==='PASS').length} passed / ${results.filter(x=>x.status==='FAIL').length} failed; ${calls.length} actual handler calls`);if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
