import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {NextRequest} from 'next/server';
const T=path.dirname(fileURLToPath(import.meta.url));const fixture=fs.mkdtempSync('/tmp/xt-leave-regression-');process.env.DB_PATH=path.join(fixture,'synthetic.db');process.env.JWT_SECRET='only-synthetic-positive-jwt';Object.assign(process.env,{NODE_ENV:'test'});delete process.env.CUSTOMER_SYNC_URL;delete process.env.SYNC_SECRET;process.chdir(fixture);fs.mkdirSync('uploads');globalThis.fetch=async()=>{throw new Error('NETWORK_DISABLED')};
const mod=(p:string)=>import(path.join(process.env.INTERNAL_SOURCE_ROOT || path.dirname(T),'src',p));const {getDb}=await mod('lib/db.ts');const {signToken}=await mod('lib/auth.ts');const db=getDb();const identities:any={};
for(const [role,name,actual] of [['client','BUYER_A','client'],['staff','WORKER_A','employee'],['admin','ADMIN_A','admin']]){const id=Number(db.prepare('INSERT INTO employees(name,email,role,password,must_change_password,auth_version) VALUES (?,?,?,?,0,0)').run(name,`${role}@synthetic.invalid`,actual,'unused').lastInsertRowid);identities[role]={id,name,role:actual,token:await signToken({id,name,role:actual,auth_version:0,must_change_password:0})};}
const ctx=(id:string,stepId?:number)=>({params:Promise.resolve({id,stepId:stepId?.toString()})});const calls:any[]=[];const results:any[]=[];
async function call(p:string,method:string,role:string|null,body?:any,context?:any,query=''){const r=await mod(`app/api/${p}/route.ts`);const res=await r[method](new NextRequest(`http://127.0.0.1/api/${p}${query}`,{method,headers:{...(role?{authorization:`Bearer ${identities[role].token}`}:{ }),'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}),context);const text=await res.text();let output:any;try{output=JSON.parse(text)}catch{output=text}const x={p,method,role,input:body,params:context?await context.params:null,status:res.status,output};calls.push(x);return x;}
async function test(name:string,fn:()=>Promise<any>){try{const detail=await fn();results.push({name,status:'PASS',detail});}catch(e){results.push({name,status:'FAIL',error:String(e),stack:(e as Error).stack});}console.log(JSON.stringify(results.at(-1)));}

await test('all six UI and schema leave options accepted by actual API',async()=>{const schema=db.prepare("SELECT sql FROM sqlite_master WHERE name='leave_requests'").get().sql;const output=[];for(const leave_type of ['事假','病假','年假','调休','法定假日','其他']){const result=await call('leave','POST','staff',{leave_type,start_date:'2026-09-15',end_date:'2026-09-15',reason:'synthetic review'});assert.equal(result.status,201);assert(schema.includes(`'${leave_type}'`));output.push({type:leave_type,status:result.status,body:result.output});}return{classification:'REGRESSION_PASS',output};});
await test('overdue leave notification still works despite stale enum registration',async()=>{db.prepare("UPDATE leave_requests SET created_at='2026-01-01 00:00:00' WHERE employee_name='WORKER_A'").run();const before=db.prepare("SELECT count(*) n FROM notifications WHERE type='leave_overdue'").get().n;const r=await call('leave','GET','admin');assert.equal(r.status,200);const after=db.prepare("SELECT count(*) n FROM notifications WHERE type='leave_overdue'").get().n;assert(after>before);return{status:200,createdOverdueNotifications:after-before,classification:'PASS_CONTROL_STALE_ENUM_NOT_ACTUAL_FAILURE_ON_THIS_PATH'};});
await test('invalid leave type rejected without inserting a row',async()=>{const before=db.prepare('SELECT count(*) n FROM leave_requests').get().n;const r=await call('leave','POST','staff',{leave_type:'NOT_A_TYPE',start_date:'2026-09-15',end_date:'2026-09-15',reason:'test'});assert.equal(r.status,400);assert.equal(db.prepare('SELECT count(*) n FROM leave_requests').get().n,before)});
fs.writeFileSync(path.join(process.env.EVIDENCE_DIR||T,'enum-dynamic-results.json'),JSON.stringify({fixture,results,calls},null,2));console.log(`POSITIVE SUMMARY ${results.filter(r=>r.status==='PASS').length} passed / ${results.filter(r=>r.status==='FAIL').length} failed; ${calls.length} handler calls`);db.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
