import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {NextRequest} from 'next/server';
const T=process.env.INTERNAL_ACCESS_RECORD_DIR!;assert(T && path.isAbsolute(T));fs.mkdirSync(T,{recursive:true});const sourceRoot=process.env.INTERNAL_ACCESS_SOURCE_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');const fixture=fs.mkdtempSync(path.join(T,'positive-data-'));process.env.DB_PATH=path.join(fixture,'synthetic.db');process.env.JWT_SECRET='only-synthetic-positive-jwt';Object.assign(process.env,{NODE_ENV:'test',ALLOW_EMPTY_DB:'1'});delete process.env.CUSTOMER_SYNC_URL;delete process.env.SYNC_SECRET;process.chdir(fixture);fs.mkdirSync('uploads');globalThis.fetch=async()=>{throw new Error('NETWORK_DISABLED')};
const mod=(p:string)=>import(path.join(sourceRoot,'src',p));const {getDb}=await mod('lib/db.ts');const {signToken}=await mod('lib/auth.ts');const db=getDb();const identities:any={};
for(const [role,name,actual] of [['client','BUYER_A','client'],['staff','WORKER_A','employee'],['admin','ADMIN_A','admin']]){const id=Number(db.prepare('INSERT INTO employees(name,email,role,password,must_change_password,auth_version) VALUES (?,?,?,?,0,0)').run(name,`${role}@synthetic.invalid`,actual,'unused').lastInsertRowid);identities[role]={id,name,role:actual,token:await signToken({id,name,role:actual,auth_version:0,must_change_password:0})};}
const ctx=(id:string,stepId?:number)=>({params:Promise.resolve({id,stepId:stepId?.toString()})});const calls:any[]=[];const results:any[]=[];
async function call(p:string,method:string,role:string|null,body?:any,context?:any,query=''){const r=await mod(`app/api/${p}/route.ts`);const res=await r[method](new NextRequest(`http://127.0.0.1/api/${p}${query}`,{method,headers:{...(role?{authorization:`Bearer ${identities[role].token}`}:{ }),'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}),context);const text=await res.text();let output:any;try{output=JSON.parse(text)}catch{output=text}const x={p,method,role,input:body,params:context?await context.params:null,status:res.status,output};calls.push(x);return x;}
async function test(name:string,fn:()=>Promise<any>){try{const detail=await fn();results.push({name,status:'PASS',detail});}catch(e){results.push({name,status:'FAIL',error:String(e),stack:(e as Error).stack});}console.log(JSON.stringify(results.at(-1)));}
const totalchanges=()=>db.prepare('SELECT total_changes() n').get().n;
const endpoints:any[]=[['employees','GET'],['employees','PATCH',{id:identities.client.id,name:'BAD'}],['orders','POST',{customer_name:'BAD',business_type_id:1}],['orders/[id]','GET'],['orders/[id]','PATCH',{description:'BAD'}],['orders/[id]','DELETE'],['orders/[id]/feedback-token','POST',{}],['vat/records/[id]','GET'],['wht/records/[id]','GET'],['factories','PATCH',{id:1,notes:'BAD'}],['influencers/[id]/finances','POST',{type:'expense',amount:1}],['logistics','POST',{cabinet_number:'BAD',warehouse:'义乌'}],['logistics/[id]/files','POST',{name:'BAD',url:'/api/files/bad.pdf'}],['logistics/[id]/files','DELETE'],['orders/[id]/documents','GET'],['orders/[id]/documents','POST',{name:'BAD'}],['orders/[id]/documents','DELETE',{document_id:1}],['orders/[id]/finances','POST',{type:'income',amount:1}],['orders/[id]/steps','PATCH',{step_id:1,status:'已完成'}],['orders/[id]/steps/[stepId]/notes','GET'],['orders/[id]/steps/[stepId]/notes','POST',{content:'BAD'}],['external/orders/[id]','GET']];
await test('anonymous role matrix: 22 actual protected handler methods -> 401 with no DB writes',async()=>{const start=totalchanges();for(const [p,method,body] of endpoints){const r=await call(p,method,null,body,ctx('NO_ORDER',1));assert.equal(r.status,401,`${p} ${method}`)}assert.equal(totalchanges(),start);return{methods:endpoints.length,noDBWrites:true}});
await test('administrator mapping grants only selected old customer and employee cannot change mapping',async()=>{let r=await call('employees','PATCH','staff',{id:identities.client.id,customer_names:['OTHER_CO']});assert.equal(r.status,403);r=await call('employees','PATCH','admin',{id:identities.client.id,customer_names:['BUYER_A']});assert.equal(r.status,200);return{staff:403,admin:200}});
for(const role of ['staff','admin'])await test(`${role} original order workflow: create -> documents/notes/finance -> process all template steps -> delete`,async()=>{let r=await call('orders','POST',role,{customer_name:'BUYER_A',business_type_id:1,total_amount:100,currency:'CNY',responsible_person:identities[role].name});assert.equal(r.status,201);const id=r.output.id;const c=ctx(id);let detail=await call('orders/[id]','GET',role,undefined,c);assert.equal(detail.status,200);const steps=detail.output.steps;assert(steps.length>0);const stepdocs=db.prepare('SELECT count(*) n FROM step_documents WHERE order_id=?').get(id).n;
const clientView=await call('external/orders/[id]','GET','client',undefined,c);assert.equal(clientView.status,200);
const rejects=[['orders','POST',{customer_name:'NO',business_type_id:1}],['orders/[id]','PATCH',{description:'BAD'}],['orders/[id]','DELETE',undefined],['orders/[id]/steps','PATCH',{step_id:steps[0].id,status:'已完成'}],['orders/[id]/finances','POST',{type:'expense',amount:1}],['orders/[id]/documents','DELETE',{document_id:1}]];const start=totalchanges();for(const [p,m,b]of rejects){const denied=await call(p as string,m as string,'client',b,c);assert.equal(denied.status,403,`${p} ${m}`)}assert.equal(totalchanges(),start);
const d=await call('orders/[id]/documents','POST',role,{name:'Synthetic submitted document',status:'待审核',uploaded_by:identities[role].name},c);assert.equal(d.status,201);const n=await call('orders/[id]/steps/[stepId]/notes','POST',role,{content:'Synthetic progress',created_by:identities[role].name},ctx(id,steps[0].id));assert.equal(n.status,201);
for(const [type,amount]of [['income',100],['expense',30]]){const f=await call('orders/[id]/finances','POST',role,{type,amount,currency:'CNY'},c);assert.equal(f.status,201)}
for(const step of steps){const begin=await call('orders/[id]/steps','PATCH',role,{step_id:step.id,status:'进行中'},c);assert.equal(begin.status,200);assert(begin.output.started_at);const done=await call('orders/[id]/steps','PATCH',role,{step_id:step.id,status:'已完成'},c);assert.equal(done.status,200);assert(done.output.completed_at)}
detail=await call('orders/[id]','GET',role,undefined,c);assert.equal(detail.output.status,'已完成');const fin=await call('orders/[id]/finances','GET',role,undefined,c);assert.equal(fin.output.length,2);
const validDelete=await call('orders/[id]','DELETE',role,undefined,c);assert.equal(validDelete.status,200);for(const table of ['orders','order_steps','step_documents','documents','step_notes','finances']){const key=table==='orders'?'id':'order_id';assert.equal(db.prepare(`SELECT count(*) n FROM ${table} WHERE ${key}=?`).get(id).n,0)}return{id,templateSteps:steps.length,templateDocuments:stepdocs,clientRead:200,clientProhibitedWrites:rejects.length,orderStatus:'已完成',deleteCascade:'no residual children'};
});
await test('unrelated legacy order access and document/finance/step reads/writes stay outside client scope',async()=>{db.prepare("INSERT INTO orders(id,customer_name,business_type_id) VALUES ('BOUNDARY_OTHER','OTHER_CO',1)").run();const st=Number(db.prepare("INSERT INTO order_steps(order_id,step_name,step_order) VALUES ('BOUNDARY_OTHER','Private step',1)").run().lastInsertRowid);const c=ctx('BOUNDARY_OTHER',st);const start=totalchanges();for(const [p,m,b,expected]of [['orders/[id]','GET',undefined,404],['external/orders/[id]','GET',undefined,404],['orders/[id]/documents','GET',undefined,403],['orders/[id]/documents','POST',{name:'BAD'},403],['orders/[id]/finances','GET',undefined,403],['orders/[id]/steps/[stepId]/notes','GET',undefined,403],['orders/[id]/steps/[stepId]/notes','POST',{content:'BAD'},403]]){assert.equal((await call(p as string,m as string,'client',b,c)).status,expected)}assert.equal(totalchanges(),start);return{deniedMethods:7,noWrites:true}});
await test('well-scoped step PATCH and document/finance DELETE reject mismatched parent keys',async()=>{db.prepare("INSERT INTO orders(id,customer_name,business_type_id) VALUES ('BOUNDARY_OWN','BUYER_A',1)").run();const step=Number(db.prepare("INSERT INTO order_steps(order_id,step_name,step_order) VALUES ('BOUNDARY_OTHER','Other',2)").run().lastInsertRowid);const d=Number(db.prepare("INSERT INTO documents(order_id,name) VALUES ('BOUNDARY_OTHER','Other document')").run().lastInsertRowid);const f=Number(db.prepare("INSERT INTO finances(order_id,type,amount) VALUES ('BOUNDARY_OTHER','income',25)").run().lastInsertRowid);const start=totalchanges();for(const [p,m,b]of [['orders/[id]/steps','PATCH',{step_id:step,status:'已完成'}],['orders/[id]/documents','DELETE',{document_id:d}],['orders/[id]/finances','DELETE',{finance_id:f}]])assert.equal((await call(p as string,m as string,'staff',b,ctx('BOUNDARY_OWN'))).status,404);assert.equal(totalchanges(),start);return{rejected:3,status:404,noWrites:true}});
await test('current employee role changes apply immediately to previously signed token',async()=>{db.prepare("UPDATE employees SET role='client' WHERE id=?").run(identities.staff.id);assert.equal((await call('orders','POST','staff',{customer_name:'BAD',business_type_id:1})).status,403);db.prepare("UPDATE employees SET role='employee' WHERE id=?").run(identities.staff.id);return{oldTokenNowClient:403}});
fs.writeFileSync(path.join(T,'positive-results.json'),JSON.stringify({fixture,results,calls},null,2));console.log(`POSITIVE SUMMARY ${results.filter(r=>r.status==='PASS').length} passed / ${results.filter(r=>r.status==='FAIL').length} failed; ${calls.length} handler calls`);db.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
