/** Route export fix regression: real handlers, JWT, SQLite; no password or tax policy changes. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import {NextRequest} from 'next/server';
const root=path.resolve(process.env.ROUTE_HELPER_SOURCE_ROOT || path.join(path.dirname(fileURLToPath(import.meta.url)),'..'));
const evidence=process.env.ROUTE_HELPER_RECORD_DIR!;assert(path.isAbsolute(evidence));fs.mkdirSync(evidence,{recursive:true});
const fixture=fs.mkdtempSync('/tmp/xt-route-helpers-');Object.assign(process.env,{DB_PATH:path.join(fixture,'synthetic.db'),NODE_ENV:'test',ALLOW_EMPTY_DB:'1',JWT_SECRET:'synthetic-route-helper-regression'});delete process.env.SYNC_SECRET;delete process.env.CUSTOMER_SYNC_URL;process.chdir(fixture);globalThis.fetch=async()=>{throw Error('NETWORK_DISABLED')};
const mod=(p:string)=>import(path.join(root,'src',p));const db=(await mod('lib/db.ts')).getDb();
const auth=await mod('lib/auth.ts');const bcrypt=(await import('bcryptjs')).default;
const password='Original123!';const employee=Number(db.prepare("INSERT INTO employees(name,email,role,password,must_change_password,auth_version) VALUES('Fixture','helpers@example.invalid','employee',?,0,0)").run(await bcrypt.hash(password,10)).lastInsertRowid);
const token=await auth.signToken({id:employee,name:'Fixture',role:'employee',auth_version:0,must_change_password:0});
const calls:any[]=[],results:any[]=[];
const req=(p:string,method:string,body:any)=>new NextRequest('http://127.0.0.1'+p,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});
async function call(p:string,method:string,body:any,id?:number){const route=await mod('app/api/'+p+'/route.ts');const r=await route[method](req('/api/'+p,method,body),{params:Promise.resolve({id:String(id)})});const value=await r.json();const out={path:p,method,input:body,id,status:r.status,body:value};calls.push(out);return out}
async function test(name:string,fn:()=>Promise<any>){try{results.push({name,status:'PASS',detail:await fn()})}catch(error){results.push({name,status:'FAIL',error:String(error)})}console.log(JSON.stringify(results.at(-1)))}
const routes=['auth/change-password','vat/records/[id]','wht/records'];
const hashes:Record<string,string>={};for(const p of routes){const full=path.join(root,'src/app/api',p,'route.ts');hashes[full]=createHash('sha256').update(fs.readFileSync(full)).digest('hex')}
const policy=fs.existsSync(path.join(root,'src/lib/password-policy.ts'))?await mod('lib/password-policy.ts'):await mod('app/api/auth/change-password/route.ts');
const vat=fs.existsSync(path.join(root,'src/lib/vat-reconciliation.ts'))?await mod('lib/vat-reconciliation.ts'):await mod('app/api/vat/records/[id]/route.ts');
const wht=fs.existsSync(path.join(root,'src/lib/wht-templates.ts'))?await mod('lib/wht-templates.ts'):await mod('app/api/wht/records/route.ts');
await test('route modules export only supported handlers/config',async()=>{const legal=new Set(['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS','dynamic','dynamicParams','revalidate','fetchCache','runtime','preferredRegion','maxDuration','generateStaticParams','config']);const invalid:any[]=[];for(const p of routes){for(const name of Object.keys(await mod('app/api/'+p+'/route.ts')))if(!legal.has(name))invalid.push({route:p,name})}assert.deepEqual(invalid,[]);return{routes:3}});
await test('password boundary results preserve exact existing messages',async()=>{const cases:any[]=[[null,'请输入新密码'],[123,'请输入新密码'],['','请输入新密码'],['1234567','新密码至少 8 位'],['password','这个密码太常见了，换一个'],['a'.repeat(8),'新密码需要包含数字或符号'],['8'.repeat(8),'新密码不能全是数字'],['Xiang2026!',null],['中'.repeat(24),null],['中'.repeat(25),'新密码不能超过 72 字节（中文通常每个字占 3 字节）'],['a'.repeat(71)+'!',null],['a'.repeat(72)+'!','新密码不能超过 72 字节（中文通常每个字占 3 字节）']];for(const [input,expected]of cases)assert.equal(policy.validatePassword(input),expected);assert.equal(policy.validatePassword('Original123!','Original123!'),'新密码不能和当前密码相同');return{cases:13}});
await test('VAT helper sums month and keeps paid value in every update',async()=>{const id=Number(db.prepare("INSERT INTO vat_customers(company_name,tax_id) VALUES('Synthetic VAT','VAT-FIXTURE')").run().lastInsertRowid);db.prepare("INSERT INTO vat_records(customer_id,year_month,amount) VALUES(?,'2026-09',100),(?,'2026-09',25),(?,'2026-10',999)").run(id,id,id);vat.syncVatReconciliation(db,id,'2026-09');const read=()=>db.prepare("SELECT tax_payable,tax_paid,tax_unpaid FROM vat_reconciliation WHERE customer_id=? AND year_month='2026-09'").get(id);assert.deepEqual(read(),{tax_payable:125,tax_paid:0,tax_unpaid:125});db.prepare("UPDATE vat_reconciliation SET tax_paid=100 WHERE customer_id=?").run(id);db.prepare("UPDATE vat_records SET amount=40 WHERE customer_id=? AND year_month='2026-09'").run(id);vat.syncVatReconciliation(db,id,'2026-09');assert.deepEqual(read(),{tax_payable:80,tax_paid:100,tax_unpaid:0});const record=db.prepare("SELECT id FROM vat_records WHERE customer_id=? AND year_month='2026-09' LIMIT 1").get(id);const changed=await call('vat/records/[id]','PATCH',{amount:80},record.id);assert.equal(changed.status,200);assert.deepEqual(read(),{tax_payable:120,tax_paid:100,tax_unpaid:20});return{created:125,updated:80,paidPreserved:100,handlerUpdated:120}});
await test('WHT accepted subtypes and their seeded workflow do not change',async()=>{assert.deepEqual(wht.WHT_SUBTYPES,['ภ.ง.ด.1','ภ.ง.ด.53']);const id=Number(db.prepare("INSERT INTO wht_customers(company_name,tax_id) VALUES('Synthetic WHT','WHT-FIXTURE')").run().lastInsertRowid);for(const [subtype,count]of [['ภ.ง.ด.1',6],['ภ.ง.ด.53',7]]as const){const r=await call('wht/records','POST',{customer_id:id,year_month:'2026-09',subtype});assert.equal(r.status,201);const steps=db.prepare('SELECT step_name,assignee,status FROM wht_record_steps WHERE record_id=? ORDER BY step_order').all(r.body.id);assert.equal(steps.length,count);assert.equal(steps[0].assignee,'Eve');if(subtype==='ภ.ง.ด.1')assert.equal(steps[2].status,'已跳过');assert.equal((await call('wht/records','POST',{customer_id:id,year_month:'2026-09',subtype})).status,409)}const before=db.prepare('SELECT count(*) n FROM wht_records').get().n;assert.equal((await call('wht/records','POST',{customer_id:id,year_month:'2026-10',subtype:'invalid'})).status,400);assert.equal((await call('wht/records','POST',{action:'generate',month:'2026-10',subtype:'invalid'})).status,400);assert.equal(db.prepare('SELECT count(*) n FROM wht_records').get().n,before);return{subtypes:2,steps:[6,7],duplicates:409,invalid:400}});
await test('password HTTP policy and reset session semantics remain unchanged',async()=>{const initial=db.prepare('SELECT password,auth_version,must_change_password FROM employees WHERE id=?').get(employee);for(const input of [{current_password:password,new_password:'short'},{current_password:password,new_password:password},{current_password:password,new_password:'中'.repeat(25)}]){assert.equal((await call('auth/change-password','POST',input)).status,400);assert.deepEqual(db.prepare('SELECT password,auth_version,must_change_password FROM employees WHERE id=?').get(employee),initial)}assert.equal((await call('auth/change-password','POST',{current_password:'Wrong123!',new_password:'FreshPassword12!'})).status,401);const ok=await call('auth/change-password','POST',{current_password:password,new_password:'FreshPassword12!'});assert.equal(ok.status,200);const changed=db.prepare('SELECT password,auth_version,must_change_password FROM employees WHERE id=?').get(employee);assert(await bcrypt.compare('FreshPassword12!',changed.password));assert.equal(changed.auth_version,1);assert.equal(changed.must_change_password,0);assert.equal(await auth.verifyToken(token),null);return{changed:200,oldTokenRevoked:true,forcedPolicyUnchanged:true}});
fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify({root,fixture,hashes,results,calls},null,2));db.close();const failed=results.filter(r=>r.status==='FAIL').length;console.log(`ROUTE HELPERS ${results.length-failed} passed / ${failed} failed`);if(failed)process.exitCode=1;
